name: app_400_gramas
description: Aplicativo 400Gramas.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  dio: ^4.0.6
  get_it: ^7.2.0
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  build_runner: ^2.2.1
  json_serializable: ^6.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/ic_logo.png"
  adaptive_icon_background: "#F0F0F0"
  adaptive_icon_foreground: "lib/assets/icon/ic_logo_foreground.png"

flutter:
  assets:
    - .env
    - lib/assets/images/
  uses-material-design: true
